sudo: false

cache:
  directories:
    - node_modules
    - test/elm-stuff/build-artifacts
    
before_script:
  - nvm install stable
  - nvm use stable
  - npm install elm
  - elm-package install -y
  - npm install elm-test

script:
  - elm-test

notifications:
  email: false
