cache:
  directories:
    - test/elm-stuff/build-artifacts
    
before_script:
  - nvm install stable
  - nvm use stable
  - npm install -g elm
  - elm-package install -y
  - npm install -g elm-test

script:
  - elm-test

notifications:
  email: false
